apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*    
build:
  local:
    push: false
  artifacts:
    - image: lucaslorenzo/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: . 
    - image: lucaslorenzo/client    
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .  
    - image: lucaslorenzo/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .           
    - image: lucaslorenzo/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .           
    - image: lucaslorenzo/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: lucaslorenzo/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .